set_property IOB TRUE [get_ports {adc_data_0[*]}]
set_property IOB TRUE [get_ports {adc_data_1[*]}]
set_property IOB TRUE [get_ports {dac_data_0[*]}]
set_property IOB TRUE [get_ports {dac_data_1[*]}]
set_property IOB TRUE [get_ports adc_clk_0]
set_property IOB TRUE [get_ports adc_clk_1]
set_property IOB TRUE [get_ports dac_clk_0]
set_property IOB TRUE [get_ports dac_clk_1]

set_property PACKAGE_PIN L14 [get_ports {dac_data_0[7]}]
set_property PACKAGE_PIN J14 [get_ports {dac_data_0[6]}]
set_property PACKAGE_PIN K14 [get_ports {dac_data_0[5]}]
set_property PACKAGE_PIN G15 [get_ports {dac_data_0[4]}]
set_property PACKAGE_PIN H15 [get_ports {dac_data_0[3]}]
set_property PACKAGE_PIN F17 [get_ports {dac_data_0[2]}]
set_property PACKAGE_PIN F16 [get_ports {dac_data_0[1]}]
set_property PACKAGE_PIN D18 [get_ports {dac_data_0[0]}]
set_property PACKAGE_PIN K19 [get_ports adc_clk_0]
set_property PACKAGE_PIN L15 [get_ports dac_clk_0]

set_property PACKAGE_PIN J20 [get_ports {adc_data_0[7]}]
set_property PACKAGE_PIN H20 [get_ports {adc_data_0[6]}]
set_property PACKAGE_PIN J18 [get_ports {adc_data_0[5]}]
set_property PACKAGE_PIN H18 [get_ports {adc_data_0[4]}]
set_property PACKAGE_PIN G19 [get_ports {adc_data_0[3]}]
set_property PACKAGE_PIN G20 [get_ports {adc_data_0[2]}]
set_property PACKAGE_PIN F19 [get_ports {adc_data_0[1]}]
set_property PACKAGE_PIN F20 [get_ports {adc_data_0[0]}]

set_property PACKAGE_PIN E17 [get_ports dac_clk_1]
set_property PACKAGE_PIN J19 [get_ports {adc_data_1[0]}]
set_property PACKAGE_PIN K17 [get_ports {adc_data_1[1]}]
set_property PACKAGE_PIN K18 [get_ports {adc_data_1[2]}]
set_property PACKAGE_PIN L16 [get_ports {adc_data_1[3]}]
set_property PACKAGE_PIN L17 [get_ports {adc_data_1[4]}]
set_property PACKAGE_PIN L19 [get_ports {adc_data_1[5]}]
set_property PACKAGE_PIN L20 [get_ports {adc_data_1[6]}]
set_property PACKAGE_PIN M19 [get_ports {adc_data_1[7]}]
set_property PACKAGE_PIN M20 [get_ports adc_clk_1]

set_property PACKAGE_PIN B19 [get_ports {dac_data_1[7]}]
set_property PACKAGE_PIN A20 [get_ports {dac_data_1[6]}]
set_property PACKAGE_PIN C20 [get_ports {dac_data_1[5]}]
set_property PACKAGE_PIN B20 [get_ports {dac_data_1[4]}]
set_property PACKAGE_PIN D19 [get_ports {dac_data_1[3]}]
set_property PACKAGE_PIN D20 [get_ports {dac_data_1[2]}]
set_property PACKAGE_PIN E18 [get_ports {dac_data_1[1]}]
set_property PACKAGE_PIN E19 [get_ports {dac_data_1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data_1[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data_1[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports adc_clk_1]
set_property IOSTANDARD LVCMOS33 [get_ports dac_clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports dac_clk_1]

set_property PACKAGE_PIN T17 [get_ports clk_adj1_out]
set_property PACKAGE_PIN R16 [get_ports clk_adj2_out]
set_property PACKAGE_PIN U14 [get_ports clk_adj3_out]
set_property IOSTANDARD LVCMOS33 [get_ports clk_adj1_out]
set_property IOSTANDARD LVCMOS33 [get_ports clk_adj2_out]
set_property IOSTANDARD LVCMOS33 [get_ports clk_adj3_out]

set_false_path -to [get_ports {clk_adj1_out clk_adj2_out clk_adj3_out}]

# Source synchronous ADC and DAC timing, adapted from ACM2108V1 to the V2
# top-level port names and RTL hierarchy.

create_generated_clock -name adc0_fwd_clk -source [get_pins -quiet -filter {REF_PIN_NAME == C} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/u_adc_clk0_oddr}]] -divide_by 1 [get_ports adc_clk_0]
set_input_delay -clock [get_clocks adc0_fwd_clk] -max 3.000 [get_ports {adc_data_0[*]}]
set_input_delay -clock [get_clocks adc0_fwd_clk] -min -1.000 [get_ports {adc_data_0[*]}]

create_generated_clock -name adc1_fwd_clk -source [get_pins -quiet -filter {REF_PIN_NAME == C} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/u_adc_clk1_oddr}]] -divide_by 1 [get_ports adc_clk_1]
set_input_delay -clock [get_clocks adc1_fwd_clk] -max 3.000 [get_ports {adc_data_1[*]}]
set_input_delay -clock [get_clocks adc1_fwd_clk] -min -1.000 [get_ports {adc_data_1[*]}]

create_generated_clock -name dac0_fwd_clk -source [get_pins -quiet -filter {REF_PIN_NAME == C} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/u_dac_clk0_oddr}]] -divide_by 1 -invert [get_ports dac_clk_0]
set_output_delay -clock [get_clocks dac0_fwd_clk] -max 3.000 [get_ports {dac_data_0[*]}]
set_output_delay -clock [get_clocks dac0_fwd_clk] -min -1.000 [get_ports {dac_data_0[*]}]

create_generated_clock -name dac1_fwd_clk -source [get_pins -quiet -filter {REF_PIN_NAME == C} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/u_dac_clk1_oddr}]] -divide_by 1 -invert [get_ports dac_clk_1]
set_output_delay -clock [get_clocks dac1_fwd_clk] -max 3.000 [get_ports {dac_data_1[*]}]
set_output_delay -clock [get_clocks dac1_fwd_clk] -min -1.000 [get_ports {dac_data_1[*]}]

set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/adc_reset_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/dac_reset_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/adc_enable_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/adc_fifo_reset_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/adc_fifo_full_axi_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/dac0_fifo_empty_axi_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/dac1_fifo_empty_axi_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/dsp0_fifo_full_axi_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/dsp1_fifo_full_axi_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/adc_single_shot_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/meas_enable_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/adc_ctrl_adc_meta_reg[*]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/meas_window_adc_meta_reg[*]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/meas_done_toggle_axi_sync_reg[0]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/meas_ch0_minmax_reg[*]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/meas_ch1_minmax_reg[*]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/meas_ch0_sum_reg[*]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/meas_ch1_sum_reg[*]}]]
set_false_path -to [get_pins -quiet -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -quiet -filter {NAME =~ */u_io_stream/meas_freq_count_reg[*]}]]

# G-problem serial screen UART, 115200 baud, 8N1.
set_property PACKAGE_PIN P14 [get_ports rx_0]
set_property PACKAGE_PIN P15 [get_ports tx_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx_0]
set_false_path -from [get_ports rx_0]
set_false_path -to [get_ports tx_0]
